/**
 * Real conflict data from verified humanitarian sources
 * Sources: UN OCHA, UNHCR, ICRC, humanitarian news (as of November 2025)
 */

export const REAL_CONFLICTS_2025 = [
  // MIDDLE EAST
  { country: "Yemen", region: "Middle East", title: "Yemen Humanitarian Emergency", summary: "Over 21.6 million people need humanitarian assistance in Yemen, making it one of the world's worst humanitarian crises. Ongoing conflict, economic collapse, and widespread disease outbreaks continue to devastate communities.", severityLevel: "Critical", affectedGroups: ["Children", "Women", "Internally Displaced", "Malnourished"], source: "reliefweb" },
  { country: "Syria", region: "Middle East", title: "Syria Humanitarian Crisis", summary: "After 12+ years of conflict, 15.3 million Syrians need humanitarian assistance. Infrastructure destruction, displacement, and economic collapse affect millions across the country.", severityLevel: "Critical", affectedGroups: ["Children", "Women", "Refugees", "Internally Displaced"], source: "reliefweb" },
  { country: "Gaza/Palestine", region: "Middle East", title: "Gaza Humanitarian Emergency", summary: "Ongoing conflict has created severe humanitarian needs affecting over 2 million people. Limited access to healthcare, clean water, and basic services continues.", severityLevel: "Critical", affectedGroups: ["Children", "Women", "Civilians", "Injured"], source: "reliefweb" },
  { country: "Lebanon", region: "Middle East", title: "Lebanon Economic & Refugee Crisis", summary: "Severe economic collapse has left 80% of the population in poverty. The healthcare system is near collapse with critical shortages in electricity, medicine, and basic services. Lebanon faces one of the worst economic crises in modern history, further strained by hosting 1.5 million refugees.", severityLevel: "High", affectedGroups: ["Elderly", "Children", "Poor", "Chronically ill"], source: "reliefweb" },
  
  // AFRICA
  { country: "Sudan", region: "Africa", title: "Sudan Conflict Crisis", summary: "Ongoing armed conflict has displaced over 7 million people. Widespread violence, food insecurity, and limited healthcare access create urgent humanitarian needs.", severityLevel: "Critical", affectedGroups: ["Internally Displaced", "Children", "Women", "Refugees"], source: "reliefweb" },
  { country: "Ethiopia", region: "Africa", title: "Ethiopia Humanitarian Emergency", summary: "Multiple conflicts and drought affect over 20 million people. Tigray region recovery continues while other areas face renewed violence and displacement.", severityLevel: "Critical", affectedGroups: ["Internally Displaced", "Drought-affected", "Children", "Malnourished"], source: "reliefweb" },
  { country: "Somalia", region: "Africa", title: "Somalia Drought & Conflict Crisis", summary: "Severe drought combined with ongoing conflict affects 8.25 million people. Widespread malnutrition, disease outbreaks, and displacement continue.", severityLevel: "Critical", affectedGroups: ["Children", "Pastoralists", "Internally Displaced", "Malnourished"], source: "reliefweb" },
  { country: "Democratic Republic of Congo", region: "Africa", title: "DRC Humanitarian Emergency", summary: "Eastern DRC faces renewed violence displacing millions. Over 26 million people need humanitarian assistance across the country.", severityLevel: "Critical", affectedGroups: ["Internally Displaced", "Women", "Children", "Refugees"], source: "reliefweb" },
  { country: "South Sudan", region: "Africa", title: "South Sudan Humanitarian Crisis", summary: "Ongoing conflict and flooding affect 9.4 million people. Widespread food insecurity, disease outbreaks, and displacement continue.", severityLevel: "Critical", affectedGroups: ["Internally Displaced", "Flood-affected", "Children", "Malnourished"], source: "reliefweb" },
  { country: "Nigeria", region: "Africa", title: "Northeast Nigeria Humanitarian Emergency", summary: "Boko Haram insurgency and farmer-herder conflicts affect 8.3 million people in northeastern states. Widespread displacement and food insecurity.", severityLevel: "High", affectedGroups: ["Internally Displaced", "Children", "Women", "Farmers"], source: "reliefweb" },
  { country: "Burkina Faso", region: "Africa", title: "Burkina Faso Conflict & Displacement Crisis", summary: "Armed group violence has displaced over 2 million people. Rapid deterioration of security situation creates widespread humanitarian needs.", severityLevel: "High", affectedGroups: ["Internally Displaced", "Children", "Women", "Farmers"], source: "reliefweb" },
  { country: "Mali", region: "Africa", title: "Mali Humanitarian Crisis", summary: "Ongoing conflict and intercommunal violence affect millions. Displacement, food insecurity, and limited access to basic services continue.", severityLevel: "High", affectedGroups: ["Internally Displaced", "Children", "Farmers", "Pastoralists"], source: "reliefweb" },
  { country: "Central African Republic", region: "Africa", title: "CAR Humanitarian Emergency", summary: "Persistent violence and displacement affect 3.4 million people. Limited state presence and ongoing armed group activity create protection concerns.", severityLevel: "High", affectedGroups: ["Internally Displaced", "Children", "Women", "Refugees"], source: "reliefweb" },
  { country: "Cameroon", region: "Africa", title: "Cameroon Humanitarian Crisis", summary: "Anglophone crisis and Boko Haram violence affect millions. Over 1 million internally displaced across multiple regions.", severityLevel: "High", affectedGroups: ["Internally Displaced", "Children", "English-speakers", "Women"], source: "reliefweb" },
  { country: "Chad", region: "Africa", title: "Chad Humanitarian Emergency", summary: "Internal displacement and food insecurity affect over 2 million Chadians. Intercommunal violence, climate-related shocks, and limited basic services create widespread humanitarian needs. The crisis is intensified by hosting hundreds of thousands of refugees fleeing conflict in Sudan.", severityLevel: "High", affectedGroups: ["Internally Displaced", "Food insecure", "Children", "Refugees"], source: "reliefweb" },
  { country: "Mozambique", region: "Africa", title: "Mozambique Cabo Delgado Crisis", summary: "Armed insurgency in northern Mozambique has displaced over 1 million people. Ongoing violence limits humanitarian access.", severityLevel: "High", affectedGroups: ["Internally Displaced", "Children", "Women", "Coastal communities"], source: "reliefweb" },
  
  // EASTERN EUROPE
  { country: "Ukraine", region: "Eastern Europe", title: "Ukraine Humanitarian Emergency", summary: "Ongoing conflict affects millions with widespread displacement. Over 17.6 million people need humanitarian assistance including internally displaced and those in conflict-affected areas.", severityLevel: "Critical", affectedGroups: ["Internally Displaced", "Elderly", "Children", "Disabled"], source: "reliefweb" },
  
  // SOUTH ASIA
  { country: "Afghanistan", region: "South Asia", title: "Afghanistan Humanitarian Crisis", summary: "Over 23 million people need humanitarian assistance following political change and economic collapse. Severe restrictions on women and girls compound humanitarian needs.", severityLevel: "Critical", affectedGroups: ["Women", "Children", "Returnees", "Drought-affected"], source: "reliefweb" },
  { country: "Pakistan", region: "South Asia", title: "Pakistan Flood Recovery & Afghan Refugees", summary: "Devastating 2022-2023 floods destroyed infrastructure and displaced millions, with recovery ongoing. Widespread food insecurity, damaged healthcare facilities, and economic challenges affect vulnerable communities. The crisis is compounded by hosting over 3 million Afghan refugees.", severityLevel: "High", affectedGroups: ["Flood-affected", "Children", "Women", "Refugees"], source: "reliefweb" },
  { country: "Myanmar", region: "Southeast Asia", title: "Myanmar Humanitarian Emergency", summary: "Military takeover and ongoing conflict affect over 17 million people. Widespread displacement, food insecurity, and limited healthcare access.", severityLevel: "Critical", affectedGroups: ["Internally Displaced", "Rohingya", "Children", "Ethnic minorities"], source: "reliefweb" },
  { country: "Bangladesh", region: "South Asia", title: "Rohingya Refugee Crisis", summary: "Host communities in Cox's Bazar face severe resource depletion, wage depression, and environmental degradation from accommodating massive refugee presence. Nearly 1 million Rohingya refugees live in overcrowded camps, creating strain on local infrastructure, healthcare, and services. Monsoon flooding and protection concerns affect both populations.", severityLevel: "High", affectedGroups: ["Host communities", "Rohingya refugees", "Children", "Women"], source: "reliefweb" },
  
  // LATIN AMERICA
  { country: "Haiti", region: "Caribbean & Latin America", title: "Haiti Humanitarian Emergency", summary: "Gang violence, political instability, and economic collapse affect millions. Widespread food insecurity and limited access to healthcare.", severityLevel: "Critical", affectedGroups: ["Internally Displaced", "Children", "Women", "Urban poor"], source: "reliefweb" },
  { country: "Venezuela", region: "Caribbean & Latin America", title: "Venezuela Humanitarian Crisis", summary: "Economic collapse has created widespread needs affecting millions. Limited access to food, medicine, and basic services continues.", severityLevel: "High", affectedGroups: ["Elderly", "Children", "Chronically ill", "Poor"], source: "reliefweb" },
  { country: "Colombia", region: "Caribbean & Latin America", title: "Colombia Displacement & Migration Crisis", summary: "Armed group violence causes ongoing internal displacement of indigenous and Afro-Colombian communities. Limited state presence in rural areas creates protection gaps and service delivery challenges. Additionally, Colombia hosts over 2.5 million Venezuelan migrants and refugees, straining public services and labor markets.", severityLevel: "High", affectedGroups: ["Internally Displaced", "Indigenous", "Afro-Colombians", "Venezuelan migrants"], source: "reliefweb" },
  
  // ADDITIONAL AFRICA CONFLICTS
  { country: "Niger", region: "Africa", title: "Niger Humanitarian Emergency", summary: "Political instability combined with armed group violence affects millions. Displacement and food insecurity continue to worsen.", severityLevel: "High", affectedGroups: ["Internally Displaced", "Children", "Refugees", "Farmers"], source: "reliefweb" },
  { country: "Kenya", region: "Africa", title: "Kenya Drought & Refugee Crisis", summary: "Severe drought in northern and eastern regions threatens food security for millions of pastoralist communities. Livestock losses, water scarcity, and malnutrition rates are rising. Kenya also hosts over 600,000 refugees, primarily in Dadaab and Kakuma camps, placing additional pressure on limited resources.", severityLevel: "High", affectedGroups: ["Drought-affected", "Pastoralists", "Children", "Refugees"], source: "reliefweb" },
  { country: "Uganda", region: "Africa", title: "Uganda Refugee Hosting Crisis", summary: "Host communities in West Nile and southwestern regions face resource depletion and service delivery challenges. Local infrastructure, healthcare facilities, and schools are overstretched. Uganda hosts over 1.5 million refugees (Africa's largest refugee-hosting nation), creating competing demands for limited public resources.", severityLevel: "Moderate", affectedGroups: ["Host communities", "South Sudanese refugees", "Congolese refugees", "Children"], source: "reliefweb" },
  { country: "Zimbabwe", region: "Africa", title: "Zimbabwe Food Security Crisis", summary: "Economic challenges and drought affect food security for millions. Limited access to healthcare and basic services.", severityLevel: "Moderate", affectedGroups: ["Rural poor", "Children", "Malnourished", "Elderly"], source: "reliefweb" },
  
  // CENTRAL ASIA
  { country: "Tajikistan", region: "Central Asia", title: "Tajikistan Border Conflict & Economic Crisis", summary: "Border clashes with Kyrgyzstan and economic challenges create humanitarian needs. Limited resources for displaced and affected populations.", severityLevel: "Moderate", affectedGroups: ["Border communities", "Internally Displaced", "Poor", "Children"], source: "reliefweb" },
  
  // ADDITIONAL MIDDLE EAST
  { country: "Iraq", region: "Middle East", title: "Iraq Displacement & Recovery", summary: "Post-ISIS recovery continues with 1.2+ million still displaced. Infrastructure needs and returnee assistance ongoing.", severityLevel: "Moderate", affectedGroups: ["Internally Displaced", "Returnees", "Children", "Minorities"], source: "reliefweb" },
  
  // ADDITIONAL ASIA
  { country: "Philippines", region: "Southeast Asia", title: "Philippines Conflict & Displacement in Mindanao", summary: "Ongoing armed group activity in Mindanao affects hundreds of thousands. Displacement and protection concerns continue.", severityLevel: "Moderate", affectedGroups: ["Internally Displaced", "Indigenous peoples", "Children", "Women"], source: "reliefweb" },
];
